# NumPy - Numerical Python
Advantages of Numpy Arrays:
1. Allows several Mathematical Operation
2. Faster operation

In [1]:
import numpy as np

List vs Numpy

In [2]:
from time import process_time

In [4]:
# Time taken by a list
python_list = [i for i in range(10000)]
start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()
end_time-start_time

0.0016160290000000188

In [8]:
np_array=np.array([i for i in range(10000)])
start_time = process_time()

np_array + 5

end_time = process_time()
end_time-start_time

0.0014565869999998426

In [9]:
list1 = [1,2,3,4,5]

In [13]:
a = np.array([1,2,3,4,5])

In [12]:
print(type(np_array))

<class 'numpy.ndarray'>


In [15]:
print(a)

[1 2 3 4 5]


In [16]:
a.shape

(5,)

In [18]:
b = np.array([a,a])
b

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [20]:
c = np.array([a,a], dtype=float)
c

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

# Initial Placeholders in numpy arrays


In [22]:
x = np.zeros((4,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
np.ones_like(a)

array([1, 1, 1, 1, 1])

In [28]:
np.full((4,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [32]:
np.random.random((3,4))

array([[0.20952988, 0.10060658, 0.48581856, 0.4081904 ],
       [0.76266728, 0.62839894, 0.89154307, 0.05762298],
       [0.59564885, 0.75103378, 0.66990906, 0.60064236]])

In [33]:
# random int values
np.random.randint(11,22, (2,4))

array([[11, 21, 20, 14],
       [19, 13, 16, 18]])

In [37]:
# array of evenly steped by mentioning number of values
d = np.linspace(10, 30, 3)
d

array([10., 20., 30.])

In [41]:
# array of evenly spaced values by mentioning step value
e = np.arange(10,30, 5)
e

array([10, 15, 20, 25])

In [44]:
list2 = [100, 20, 39, 40]
np_array = np.asarray(list2)
np_array

array([100,  20,  39,  40])

In [46]:
# Analysing numpy array
c= np.random.randint(10, 90, (5,3))
c

array([[81, 62, 58],
       [17, 19, 42],
       [66, 52, 47],
       [19, 35, 46],
       [89, 74, 19]])

In [47]:
print(c.dtype)

int64
